[package]
name = "fluvio-go"
version = "0.1.0"
authors = ["avi <hi@avi.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "fluvio_go"

[dependencies]
libc = "0.2.92"
cbindgen = "0.18.0"
fluvio = { version = "0.6.1" }
fluvio-future = { version = "0.2.0", features = ["task", "io"] }

[build-dependencies]
cbindgen = "0.18.0"
