// WARNING: This file has automatically been generated on Sun, 04 Apr 2021 17:10:42 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fluvio_cgo

/*
#cgo LDFLAGS: -L../target/debug -lfluvio_go
#include "../src/fluvio_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *Fluvio) Ref() *C.Fluvio {
	if x == nil {
		return nil
	}
	return (*C.Fluvio)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Fluvio) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewFluvioRef converts the C object reference into a raw struct reference without wrapping.
func NewFluvioRef(ref unsafe.Pointer) *Fluvio {
	return (*Fluvio)(ref)
}

// NewFluvio allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewFluvio() *Fluvio {
	return (*Fluvio)(allocFluvioMemory(1))
}

// allocFluvioMemory allocates memory for type C.Fluvio in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFluvioMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFluvioValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFluvioValue = unsafe.Sizeof([1]C.Fluvio{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Fluvio) PassRef() *C.Fluvio {
	if x == nil {
		x = (*Fluvio)(allocFluvioMemory(1))
	}
	return (*C.Fluvio)(unsafe.Pointer(x))
}
