// WARNING: This file has automatically been generated on Thu, 08 Apr 2021 22:06:47 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../src/fluvio_go.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

