// WARNING: This file has automatically been generated on Sun, 04 Apr 2021 17:55:48 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../src/fluvio_go.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

