// WARNING: This file has automatically been generated on Sun, 04 Apr 2021 17:55:48 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fluvio_cgo

/*
#cgo LDFLAGS: -L../target/debug -lfluvio_go
#include "../src/fluvio_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// Connect function as declared in src/fluvio_go.h:10
func Connect() *Fluvio {
	__ret := C.connect()
	__v := *(**Fluvio)(unsafe.Pointer(&__ret))
	return __v
}

// FluvioTopicProducer function as declared in src/fluvio_go.h:12
func FluvioTopicProducer(Ptr []Fluvio) *TopicProducer {
	cPtr, cPtrAllocMap := copyPStructFluvioBytes((*sliceHeader)(unsafe.Pointer(&Ptr)))
	__ret := C.fluvio_topic_producer(cPtr)
	runtime.KeepAlive(cPtrAllocMap)
	__v := *(**TopicProducer)(unsafe.Pointer(&__ret))
	return __v
}

// FluvioTopicProducerSend function as declared in src/fluvio_go.h:14
func FluvioTopicProducerSend(Ptr []TopicProducer) {
	cPtr, cPtrAllocMap := copyPStructTopicProducerBytes((*sliceHeader)(unsafe.Pointer(&Ptr)))
	C.fluvio_topic_producer_send(cPtr)
	runtime.KeepAlive(cPtrAllocMap)
}
