// WARNING: This file has automatically been generated on Sun, 04 Apr 2021 14:48:46 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fluvio_cgo

/*
#cgo LDFLAGS: -L../target/debug -lfluvio_go
#include "../src/fluvio_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "runtime"

// FlHelloWorld function as declared in src/fluvio_go.h:6
func FlHelloWorld() {
	C.fl_hello_world()
}

// FlAddition function as declared in src/fluvio_go.h:8
func FlAddition(A uint32, B uint32) uint32 {
	cA, cAAllocMap := (C.uint32_t)(A), cgoAllocsUnknown
	cB, cBAllocMap := (C.uint32_t)(B), cgoAllocsUnknown
	__ret := C.fl_addition(cA, cB)
	runtime.KeepAlive(cBAllocMap)
	runtime.KeepAlive(cAAllocMap)
	__v := (uint32)(__ret)
	return __v
}
