// WARNING: This file has automatically been generated on Thu, 08 Apr 2021 22:06:47 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fluvio_cgo

/*
#cgo LDFLAGS: -L../target/debug -lfluvio_go
#include "../src/fluvio_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// FluvioConnect function as declared in src/fluvio_go.h:10
func FluvioConnect() *Fluvio {
	__ret := C.fluvio_connect()
	__v := *(**Fluvio)(unsafe.Pointer(&__ret))
	return __v
}

// FluvioTopicProducer function as declared in src/fluvio_go.h:12
func FluvioTopicProducer(Ptr []Fluvio) *TopicProducer {
	cPtr, cPtrAllocMap := copyPStructFluvioBytes((*sliceHeader)(unsafe.Pointer(&Ptr)))
	__ret := C.fluvio_topic_producer(cPtr)
	runtime.KeepAlive(cPtrAllocMap)
	__v := *(**TopicProducer)(unsafe.Pointer(&__ret))
	return __v
}

// FluvioTopicProducerSend function as declared in src/fluvio_go.h:14
func FluvioTopicProducerSend(Ptr []TopicProducer, ValuePtr string) {
	cPtr, cPtrAllocMap := copyPStructTopicProducerBytes((*sliceHeader)(unsafe.Pointer(&Ptr)))
	ValuePtr = safeString(ValuePtr)
	cValuePtr, cValuePtrAllocMap := unpackPCharString(ValuePtr)
	C.fluvio_topic_producer_send(cPtr, cValuePtr)
	runtime.KeepAlive(ValuePtr)
	runtime.KeepAlive(cValuePtrAllocMap)
	runtime.KeepAlive(cPtrAllocMap)
}
