// WARNING: This file has automatically been generated on Sun, 04 Apr 2021 17:55:48 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package fluvio_cgo

/*
#cgo LDFLAGS: -L../target/debug -lfluvio_go
#include "../src/fluvio_go.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Fluvio as declared in src/fluvio_go.h:6
type Fluvio C.Fluvio

// TopicProducer as declared in src/fluvio_go.h:8
type TopicProducer C.TopicProducer
