name: release artifacts

on: [push]

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
